spring.datasource.url=jdbc:postgresql://localhost:5432/nrs_texas
spring.datasource.driver-class-name= org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8032

spring.thymeleaf.mode=LEGACYHTML5
spring.thymeleaf.cache=false

# Ehcache Configuration
spring.cache.ehcache.config=classpath:ehcache.xml

# Log4j configuration
#logging.level.org.springframework.web=INFO
#logging.level.com.sellproduct.controllers=INFO
#logging.level.org.hibernate=ERROR
#logging.file.name=logs/web-admin.log

log4j.appender.File.MaxFileSize=10MB
log4j.appender.File.MaxBackupIndex=10


spring.servlet.multipart.max-file-size=50MB